stages:
    load_data:
        cmd: python src/load_data.py --parameters_yaml_path parameters.yaml
        deps:
            - src/load_data.py
            - src/read_data.py
            - parameters.yaml
            - original_data/winequality.csv
        outs:
            - data/raw/raw_winequality.csv

    split_data:
        cmd: python src/split_data.py --parameters_yaml_path parameters.yaml
        deps:
            - src/split_data.py
            - src/read_data.py
            - parameters.yaml
            - data/raw/raw_winequality.csv
        outs:
            - data/processed/train_winequality.csv
            - data/processed/test_winequality.csv