stages:
    load_data:
        cmd: python src/load_data.py --parameters_yaml_path params.yaml
        deps:
            - src/load_data.py
            - src/read_data.py
            - params.yaml
            - original_data/winequality.csv
        outs:
            - data/raw/raw_winequality.csv

    split_data:
        cmd: python src/split_data.py --parameters_yaml_path params.yaml
        deps:
            - src/split_data.py
            - src/read_data.py
            - params.yaml
            - data/raw/raw_winequality.csv
        outs:
            - data/processed/train_winequality.csv
            - data/processed/test_winequality.csv
    
    train_and_evaluate:
        cmd: python src/train_and_evaluate.py --parameters_yaml_path params.yaml
        deps:
            - src/train_and_evaluate.py
            - src/read_data.py
            - data/processed/train_winequality.csv
            - data/processed/test_winequality.csv
            - params.yaml
        params:
            - algorithms.ElasticNet.parameters.alpha
            - algorithms.ElasticNet.parameters.l1_ratio
        metrics:
            - reports/model_scores.json:
                cache: false

            - reports/model_parameters.json:
                cache: false
        outs:
            - models/elasticnet_model.joblib
            